/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ufl_cise_klu_wrapper_SuperLUWrapper */

#ifndef _Included_edu_ufl_cise_klu_wrapper_SuperLUWrapper
#define _Included_edu_ufl_cise_klu_wrapper_SuperLUWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperLUWrapper
 * Method:    dCreate_CompCol_Matrix
 * Signature: (Ledu/ufl/cise/klu/wrapper/SuperMatrix;III[D[I[ILedu/ufl/cise/klu/wrapper/Stype_t;Ledu/ufl/cise/klu/wrapper/Dtype_t;Ledu/ufl/cise/klu/wrapper/Mtype_t;)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperLUWrapper_dCreate_1CompCol_1Matrix
  (JNIEnv *, jobject, jobject, jint, jint, jint, jdoubleArray, jintArray, jintArray, jobject, jobject, jobject);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperLUWrapper
 * Method:    dGenXtrue
 * Signature: (II[DI)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperLUWrapper_dGenXtrue
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jint);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperLUWrapper
 * Method:    dFillRHS
 * Signature: (Ledu/ufl/cise/klu/wrapper/trans_t;I[DILedu/ufl/cise/klu/wrapper/SuperMatrix;Ledu/ufl/cise/klu/wrapper/SuperMatrix;)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperLUWrapper_dFillRHS
  (JNIEnv *, jobject, jobject, jint, jdoubleArray, jint, jobject, jobject);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperLUWrapper
 * Method:    get_perm_c
 * Signature: (ILedu/ufl/cise/klu/wrapper/SuperMatrix;[I)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperLUWrapper_get_1perm_1c
  (JNIEnv *, jobject, jint, jobject, jintArray);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperLUWrapper
 * Method:    dgssv
 * Signature: ([Ledu/ufl/cise/klu/wrapper/superlu_options_t;Ledu/ufl/cise/klu/wrapper/SuperMatrix;[I[ILedu/ufl/cise/klu/wrapper/SuperMatrix;Ledu/ufl/cise/klu/wrapper/SuperMatrix;Ledu/ufl/cise/klu/wrapper/SuperMatrix;[Ledu/ufl/cise/klu/wrapper/SuperLUStat_t;[I)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperLUWrapper_dgssv
  (JNIEnv *, jobject, jobjectArray, jobject, jintArray, jintArray, jobject, jobject, jobject, jobjectArray, jintArray);

/*
 * Class:     edu_ufl_cise_klu_wrapper_SuperLUWrapper
 * Method:    dinf_norm_error
 * Signature: (ILedu/ufl/cise/klu/wrapper/SuperMatrix;[D)V
 */
JNIEXPORT void JNICALL Java_edu_ufl_cise_klu_wrapper_SuperLUWrapper_dinf_1norm_1error
  (JNIEnv *, jobject, jint, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
